### PR TITLE
Set AsyncBufferSize to default value at NewAsyncHookWithFieldsAndConnAndPrefix

### PR DESCRIPTION
**Pull request by vm-affekt**

### CODE REVIEW

**Comment by cheshir** [comment]
Hi. 

I think it's better to set `hook.AsyncBufferSize` once instead of modyfying all methods.
For example, you can do it in `makeAsync` method.

**Comment by vm-affekt** [comment]
@cheshir ok!

**Comment by vm-affekt** [comment]
I also have add check: If AsyncBufferSize is zero, then we set default value. I think that in further it will be a feature to set AsyncBufferSize in constructor

**Comment by vm-affekt** [comment]
@cheshir ping

**Comment by cheshir** [comment]
Good job!

**Pull request merged**
